import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout(props:Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex mx-auto w-full'>
            <div>
                <NavBar/>
            </div>
            <main className='w-full' >
                {props.children}
            </main>
        </div>
      </body>
    </html>
  )
}
